### ISSUE TITLE
TEST :: L7 Structs

### ISSUE THREAD

**Issue by ChrisDavison** [EE273-EE985-EngineeringDesign/ee273#1]
```c
villains[0].familyName = "Ferguson";
```

This is just an example of some formatting, and how the system would work.

**Comment by ChrisDavison** [comment]
This is a response.  Students just need an account.

Can also link to code we've created, if the discussion proves useful...

- [Namespaces](https://github.com/ChrisDavison/ee273/namespaces.md)

**Comment by christation** [comment]
This is public but if we get educational account, it can become private and we will provide an invitation link through ``myplace``.  The students then can create their own account removing the administration burden.

**Comment by christation** [comment]
Is the wiki a better place to add articles such as the [Namespaces](namespaces.md) and keep the code repository for code? As I understand it the wiki is a separate repository is that correct?

**Comment by ChrisDavison** [comment]
Wiki just as easy to use, although not sure how easy it would be to navigate.  Never used the wiki functionality, so didn't realise it could be treated like a repo and easily updated. @christation #2
